### ISSUE TITLE
KJV text?

### ISSUE THREAD

**Issue by Stratus3D** [honza/bibles#4]
Is there anyway the King James version could be added to this repo?

**Comment by honza** [comment]
I would be happy to accept a PR adding KJV to the mix. But honestly, I probably won't be working on that myself --- pretty low priority for me. Thanks

**Comment by olaolumusic** [comment]
Hi @Stratus3D , if you have any format of KJV other than Json, kindly send to me, i will parse and covert it to Json format for you.
If not, I would try make out some time to search for one myself.
Cheers

**Comment by timothy** [comment]
Here is KJV in JSON format. https://github.com/timothy/Bible-kjv

**Comment by Stratus3D** [comment]
Hi everyone, I ended up just pulling a USFX document from ebible.org. http://ebible.org/usfx/. I ended up needing more formatting information than typical JSON documents provide (e.g. italicized words in the KJV).

**Comment by olaolumusic** [comment]
Thanks @Stratus3D and @timothy 
Cheers
